SECRET_KEY_BASE: f4082baf04b77ffe4dcd4dcc52b90910deae22ab97f8e7051d2e3b9a5be0181985015ea03179d19270d8a96bf331e7d7c70662e5a6a658918ed23445e9980$

default:
  # Database
  DATABASE_ADAPTER: postgresql
  DATABASE_USER: root
  DATABASE_PASSWORD: root
  DATABASE_NAME: event_development
  DATABASE_HOST: localhost
  DOMAIN: jannahevent.herokuapp.com

development:
  # Database
  DATABASE_ADAPTER: postgresql
  DATABASE_USER: root
  DATABASE_PASSWORD: root
  DATABASE_NAME: event_development
  DATABASE_HOST: localhost
  DOMAIN: localhost

  FACEBOOK_APP_ID: 1010053535725175
  FACEBOOK_APP_SECRET: 1010053535725175

production:
  # Database
  DATABASE_ADAPTER: postgresql
  DATABASE_USER: root
  DATABASE_PASSWORD: root
  DATABASE_NAME: event_production
  DATABASE_HOST: localhost
  DOMAIN: localhost

  FACEBOOK_APP_ID: 1037096729731636
  FACEBOOK_APP_SECRET: 6703b75235b704e789aa9fbb6490badd

# Staging
